version: 2.1

workflows:
    "Hello Workflow":
        jobs:
          build:
            docker: # use the docker executor type; machine and macos executors are also supported
              - image: circleci/python@3.6.7-stretch # the primary container, where your job's commands are run
            steps:
              - checkout # check out the code in the project directory
              - run: cd ./example_project && python3 test.py # run the `echo` command
