version: 2.1

jobs:
  latex_document_build:
    docker:
      - image: koppor/texlive
    steps:
      - checkout
      - run: 
          name: Latex Generation Shell Script
          command: chmod a+x .circleci/job_document.sh && .circleci/job_document.sh
      - store_artifacts:
          path: /tmp/artifacts
  run_python_tests:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/python:latest # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Python Tests Shell Script
          command: chmod a+x .circleci/job_python.sh && .circleci/job_python.sh

workflows:
  version: 2.1
  build_and_test:
    jobs: # - latex_document_build
      - run_python_tests